name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Github Pages
      uses: actions/configure-pages@v3
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build release
      run: make all
    - name: Assemble release folder
      run: |
        mkdir release-gh-pages
        cp -r release release-gh-pages/
        cp sw.js release-gh-pages/
        cp index.css release-gh-pages/
        cp index.html release-gh-pages/
        cp manifest.json release-gh-pages/
        cp kanjiInfo.json release-gh-pages/
        cp radk.json release-gh-pages/
    - name: Upload Github Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./release-gh-pages"
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v2

